In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

In [1]:
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

import os, re

import pandas as pd  # dataframes
import numpy as np

from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.ensemble import BaggingClassifier, ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier


np.random.seed(234)

/home/olamide/anaconda3/lib/python3.5/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [2]:
#train = pd.read_csv("Devex_train.csv", encoding = "latin-1")
train = pd.read_csv("train_clean.csv")
test = pd.read_csv("Devex_test_questions.csv",encoding = "ISO-8859-1")
sub = pd.read_csv("Devex_submission_format.csv")

In [3]:
sub.head()

,ID,3.1.1,3.1.2,3.2.1,3.2.2,3.3.1,3.3.2,3.3.3,3.3.4,3.3.5,...,3.8.2,3.9.1,3.9.2,3.9.3,3.a.1,3.b.1,3.b.2,3.b.3,3.c.1,3.d.1
0,11437,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1,11474,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
2,11475,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
3,11476,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
4,11486,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0

In [4]:
test.head()

   Unique ID          Type                                               Text
0      49848  Organization  4th Sector Health: <p>4th Sector Health is a U...
1      52348  Organization  Action for Global Health: <p>Action for Global...
2     103541  Organization  Scottish Association for Mental Health (SAMH):...
3      52382  Organization  Singapore Immunology Network: <p>The Singapore...
4      47212  Organization  Coastal Conservation and Education Foundation ...

In [5]:
train.head()

,Unique ID,Type,Text,3.1.1,3.1.2,3.2.1,3.2.2,3.3.1,3.3.2,3.3.3,...,3.8.2,3.9.1,3.9.2,3.9.3,3.a.1,3.b.1,3.b.2,3.b.3,3.c.1,3.d.1
0,12555.0,Grant,Centers of Biomedical Research Excellence (COB...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
1,14108.0,Grant,Research on Regenerative Medicine Introduction...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,23168.0,Organization,Catholic Health Association of India (CHAI): T...,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,1
3,219512.0,Contract,Quality Improvement Initiatives for Diabetes,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,274093.0,Tender,Provision of Thalassemia Drugs and Disposables...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
len(train)

2995

In [7]:
cleanr = re.compile('<.*?>')

def remove_html(raw_html):
    cleantext = re.sub(cleanr, '', raw_html)
    cleantext = re.sub('&nbsp;', ' ', cleantext)
    cleantext = re.sub('&bull;', ' ', cleantext)
    return cleantext

In [8]:
for i in range(len(test)):
    test.at[i,'Text'] = remove_html(test.at[i,'Text'])

In [9]:
test = test.replace({r'\x0D': ' '}, regex=True) #removing carriage returns

In [10]:
X_train = train['Text']
X_test = test['Text']

In [11]:
word =  TfidfVectorizer(ngram_range=(1,3), analyzer='word', norm='l2', stop_words='english',
               min_df=2, max_df=0.7, strip_accents='unicode', use_idf=True,
               smooth_idf=True, sublinear_tf=1 )

In [12]:
train_1 = word.fit_transform(X_train)

In [13]:
test_1 = word.transform(X_test)

In [14]:
labels = train[train.columns[3:]]

In [15]:
lablist = train.columns[3:].tolist()

In [16]:
target = train[lablist]
tr_ids = train[['Unique ID']]

In [17]:
folds = 5
scores = []
scores_classes = np.zeros((len(labels), folds))

submission = pd.DataFrame.from_dict({'Unique ID': test['Unique ID']})

kfold = KFold(n_splits=folds, shuffle=True, random_state=1001)
for j, (label) in enumerate(labels):
    
    classifier = BaggingClassifier(DecisionTreeClassifier(), n_estimators=20)
    
    avreal = target[label]
    lr_cv_sum = []
    lr_pred = []
    lr_fpred = []
    lr_avpred = np.zeros(train_1.shape[0])
    
    for i, (train_index, val_index) in enumerate(kfold.split(train_1, target[label].values)):
        X_train, X_val = train_1[train_index], train_1[val_index]
        y_train, y_val = target.loc[train_index], target.loc[val_index]
        
        classifier.fit(X_train, y_train[label])
        
        scores_val = classifier.predict_proba(X_val)[:,1]
        lr_avpred[val_index] = scores_val
        lr_y_pred = classifier.predict_proba(test_1)[:,1]
        
        
        scores_classes[j][i] = roc_auc_score(y_val[label], scores_val)
        scores.append(scores_classes[j])
        
        print('\n Fold %02d class %s AUC: %.6f' % ((i+1), label, scores_classes[j][i]))
        
        if i > 0:
            lr_fpred = lr_pred + lr_y_pred
        else:
            lr_fpred = lr_y_pred
        
        lr_pred = lr_fpred
           
    print('\n Average class %s AUC:\t%.6f' % (label, np.mean(scores_classes[j])))
        
    submission[label] = lr_pred / folds
    sub = np.around(submission.iloc[0:]).astype('int')
    
print('\n Overall AUC:\t%.6f' % (np.mean(scores)))
sub.to_csv('submissionbgdt.csv', index=False)
submission.to_csv('submissionbgdtp.csv', index=False)

 Fold 01 class 3.1.1 AUC: 0.862053

 Fold 02 class 3.1.1 AUC: 0.869646

 Fold 03 class 3.1.1 AUC: 0.892635

 Fold 04 class 3.1.1 AUC: 0.884868

 Fold 05 class 3.1.1 AUC: 0.886685

 Average class 3.1.1 AUC:	0.879177

 Fold 01 class 3.1.2 AUC: 0.785771

 Fold 02 class 3.1.2 AUC: 0.810883

 Fold 03 class 3.1.2 AUC: 0.640797

 Fold 04 class 3.1.2 AUC: 0.783180

 Fold 05 class 3.1.2 AUC: 0.692571

 Average class 3.1.2 AUC:	0.742640

 Fold 01 class 3.2.1 AUC: 0.903247

 Fold 02 class 3.2.1 AUC: 0.922725

 Fold 03 class 3.2.1 AUC: 0.944624

 Fold 04 class 3.2.1 AUC: 0.913944

 Fold 05 class 3.2.1 AUC: 0.914399

 Average class 3.2.1 AUC:	0.919788

 Fold 01 class 3.2.2 AUC: 0.880212

 Fold 02 class 3.2.2 AUC: 0.898116

 Fold 03 class 3.2.2 AUC: 0.869654

 Fold 04 class 3.2.2 AUC: 0.891197

 Fold 05 class 3.2.2 AUC: 0.874261

 Average class 3.2.2 AUC:	0.882688

 Fold 01 class 3.3.1 AUC: 0.955033

 Fold 02 class 3.3.1 AUC: 0.962161

 Fold 03 class 3.3.1 AUC: 0.956886

 Fold 04 class 3.3.1 AUC: 0.943154

 Fold 05 class 3.3.1 AUC: 0.951907

 Average class 3.3.1 AUC:	0.953828

 Fold 01 class 3.3.2 AUC: 0.934281

 Fold 02 class 3.3.2 AUC: 0.919253

 Fold 03 class 3.3.2 AUC: 0.999015

 Fold 04 class 3.3.2 AUC: 0.952717

 Fold 05 class 3.3.2 AUC: 0.949156

 Average class 3.3.2 AUC:	0.950884

 Fold 01 class 3.3.3 AUC: 0.934235

 Fold 02 class 3.3.3 AUC: 0.940571

 Fold 03 class 3.3.3 AUC: 0.996998

 Fold 04 class 3.3.3 AUC: 0.979516

 Fold 05 class 3.3.3 AUC: 0.930140

 Average class 3.3.3 AUC:	0.956292

 Fold 01 class 3.3.4 AUC: 0.871309

 Fold 02 class 3.3.4 AUC: 0.963128

 Fold 03 class 3.3.4 AUC: 1.000000

 Fold 04 class 3.3.4 AUC: 0.806472

 Fold 05 class 3.3.4 AUC: 0.910065

 Average class 3.3.4 AUC:	0.910195

 Fold 01 class 3.3.5 AUC: 0.915874

 Fold 02 class 3.3.5 AUC: 0.936513

 Fold 03 class 3.3.5 AUC: 0.903283

 Fold 04 class 3.3.5 AUC: 0.891828

 Fold 05 class 3.3.5 AUC: 0.854338

 Average class 3.3.5 AUC:	0.900367

 Fold 01 class 3.4.1 AUC: 0.933699

 Fold 02 class 3.4.1 AUC: 0.962613

 Fold 03 class 3.4.1 AUC: 0.952663

 Fold 04 class 3.4.1 AUC: 0.962799

 Fold 05 class 3.4.1 AUC: 0.956740

 Average class 3.4.1 AUC:	0.953703

 Fold 01 class 3.4.2 AUC: 0.893436

 Fold 02 class 3.4.2 AUC: 0.996599

 Fold 03 class 3.4.2 AUC: 0.890238

 Fold 04 class 3.4.2 AUC: 0.895205

 Fold 05 class 3.4.2 AUC: 0.739559

 Average class 3.4.2 AUC:	0.883007

 Fold 01 class 3.5.1 AUC: 0.901457

 Fold 02 class 3.5.1 AUC: 0.860968

 Fold 03 class 3.5.1 AUC: 0.911080

 Fold 04 class 3.5.1 AUC: 0.824239

 Fold 05 class 3.5.1 AUC: 0.785339

 Average class 3.5.1 AUC:	0.856617

 Fold 01 class 3.5.2 AUC: 0.852112

 Fold 02 class 3.5.2 AUC: 0.857112

 Fold 03 class 3.5.2 AUC: 0.939360

 Fold 04 class 3.5.2 AUC: 0.957272

 Fold 05 class 3.5.2 AUC: 0.938521

 Average class 3.5.2 AUC:	0.908875

 Fold 01 class 3.6.1 AUC: 0.812618

 Fold 02 class 3.6.1 AUC: 0.814503

 Fold 03 class 3.6.1 AUC: 0.810403

 Fold 04 class 3.6.1 AUC: 0.822693

 Fold 05 class 3.6.1 AUC: 0.866176

 Average class 3.6.1 AUC:	0.825278

 Fold 01 class 3.7.1 AUC: 0.906876

 Fold 02 class 3.7.1 AUC: 0.913879

 Fold 03 class 3.7.1 AUC: 0.894666

 Fold 04 class 3.7.1 AUC: 0.892959

 Fold 05 class 3.7.1 AUC: 0.883260

 Average class 3.7.1 AUC:	0.898328

 Fold 01 class 3.7.2 AUC: 0.891869

 Fold 02 class 3.7.2 AUC: 0.901643

 Fold 03 class 3.7.2 AUC: 0.919948

 Fold 04 class 3.7.2 AUC: 0.841984

 Fold 05 class 3.7.2 AUC: 0.811494

 Average class 3.7.2 AUC:	0.873388

 Fold 01 class 3.8.1 AUC: 0.771366

 Fold 02 class 3.8.1 AUC: 0.749706

 Fold 03 class 3.8.1 AUC: 0.783586

 Fold 04 class 3.8.1 AUC: 0.736030

 Fold 05 class 3.8.1 AUC: 0.783109

 Average class 3.8.1 AUC:	0.764759

 Fold 01 class 3.8.2 AUC: 0.819671

 Fold 02 class 3.8.2 AUC: 0.833601

 Fold 03 class 3.8.2 AUC: 0.766895

 Fold 04 class 3.8.2 AUC: 0.776368

 Fold 05 class 3.8.2 AUC: 0.760949

 Average class 3.8.2 AUC:	0.791497

 Fold 01 class 3.9.1 AUC: 0.852002

 Fold 02 class 3.9.1 AUC: 0.740549

 Fold 03 class 3.9.1 AUC: 0.569024

 Fold 04 class 3.9.1 AUC: 0.794759

 Fold 05 class 3.9.1 AUC: 0.730586

 Average class 3.9.1 AUC:	0.737384

 Fold 01 class 3.9.2 AUC: 0.946570

 Fold 02 class 3.9.2 AUC: 0.929684

 Fold 03 class 3.9.2 AUC: 0.978179

 Fold 04 class 3.9.2 AUC: 0.895817

 Fold 05 class 3.9.2 AUC: 0.881787

 Average class 3.9.2 AUC:	0.926407

 Fold 01 class 3.9.3 AUC: 0.845432

 Fold 02 class 3.9.3 AUC: 0.634729

 Fold 03 class 3.9.3 AUC: 0.817085

 Fold 04 class 3.9.3 AUC: 0.757602

 Fold 05 class 3.9.3 AUC: 0.796190

 Average class 3.9.3 AUC:	0.770208

 Fold 01 class 3.a.1 AUC: 0.935408

 Fold 02 class 3.a.1 AUC: 0.826313

 Fold 03 class 3.a.1 AUC: 0.948557

 Fold 04 class 3.a.1 AUC: 0.954713

 Fold 05 class 3.a.1 AUC: 0.917449

 Average class 3.a.1 AUC:	0.916488

 Fold 01 class 3.b.1 AUC: 0.926851

 Fold 02 class 3.b.1 AUC: 0.827581

 Fold 03 class 3.b.1 AUC: 0.869249

 Fold 04 class 3.b.1 AUC: 0.929350

 Fold 05 class 3.b.1 AUC: 0.866043

 Average class 3.b.1 AUC:	0.883815

 Fold 01 class 3.b.2 AUC: 0.870464

 Fold 02 class 3.b.2 AUC: 0.843736

 Fold 03 class 3.b.2 AUC: 0.884418

 Fold 04 class 3.b.2 AUC: 0.862277

 Fold 05 class 3.b.2 AUC: 0.865767

 Average class 3.b.2 AUC:	0.865332

 Fold 01 class 3.b.3 AUC: 0.805817

 Fold 02 class 3.b.3 AUC: 0.847359

 Fold 03 class 3.b.3 AUC: 0.841317

 Fold 04 class 3.b.3 AUC: 0.841132

 Fold 05 class 3.b.3 AUC: 0.795891

 Average class 3.b.3 AUC:	0.826303

 Fold 01 class 3.c.1 AUC: 0.836843

 Fold 02 class 3.c.1 AUC: 0.893831

 Fold 03 class 3.c.1 AUC: 0.843406

 Fold 04 class 3.c.1 AUC: 0.901545

 Fold 05 class 3.c.1 AUC: 0.820434

 Average class 3.c.1 AUC:	0.859212

 Fold 01 class 3.d.1 AUC: 0.853390

 Fold 02 class 3.d.1 AUC: 0.872039

 Fold 03 class 3.d.1 AUC: 0.855267

 Fold 04 class 3.d.1 AUC: 0.842616

 Fold 05 class 3.d.1 AUC: 0.870997

 Average class 3.d.1 AUC:	0.858862

 Overall AUC:	0.870197